/* 
TRUY VẤN TẬP HỢP: UNION (HỘI), INTERSECT (GIAO), EXCEPT (TRỪ)
    SELECT A, B ...
    UNION|INTERSECTION|EXCEPT
    SELECT C, D ...
    
ĐIỀU KIỆN: SỐ LƯỢNG CỘT TRẢ RA Ở CÂU TRUY VẤN TRƯỚC VÀ SAU UNION|INTERSECT|EXCEPT PHẢI = NHAU VÀ
LẦN LƯỢT TƯƠNG ĐỒNG KIỂU DỮ LIỆU
*/

/*LUYỆN TẬP: SỬ DỤNG TRUY VẤN TẬP HỢP CHO CÁC TRUY VẤN SAU
1. CHO TRƯỞNG KHOA (MÃ GV, HỌ TÊN, TÊN KHOA) CỦA KHOA CÓ SỐ LƯỢNG BỘ MÔN NHIỀU NHẤT HOẶC CÓ LƯƠNG TRUNG BÌNH CỦA GIÁO VIÊN CAO NHẤT
2. CHO GIÁO VIÊN (MÃ GV, HỌ TÊN) CỦA GIÁO VIÊN CÓ THAM GIA ĐỀ TÀI CẤP TRƯỜNG NHƯNG KHÔNG CHỦ NHIỆM ĐỀ TÀI NÀO CẤP TRƯỜNG
3. CHO TRƯỞNG BỘ MÔN CÓ CHỦ NHIỆM ÍT NHẤT MỘT ĐỀ TÀI CẤP NHÀ NƯỚC VÀ THAM GIA BẤT KỲ ĐỀ TÀI NÀO CÓ CÔNG VIỆC LIÊN QUAN ĐẾN "NUÔI CẤY".
4. CHO GIÁO VIÊN (MÃ, HỌ TÊN) CHỈ THAM GIA ĐỀ TÀI CẤP NHÀ NƯỚC.
5. 
*/

--1. CHO TRƯỞNG KHOA (MÃ GV, HỌ TÊN, TÊN KHOA) CỦA KHOA 
--   CÓ SỐ LƯỢNG BỘ MÔN NHIỀU NHẤT 
--   HOẶC CÓ LƯƠNG TRUNG BÌNH CỦA GIÁO VIÊN CAO NHẤT
--1. CÁCH 1: HỘI HAI TRƯỞNG KHOA
SELECT TRKHOA.MAGV, TRKHOA.HOTEN, K.TENKHOA -- TRƯỞNG KHOA CỦA KHOA NHIỀU BỘ MÔN NHẤT
FROM GIAOVIEN TRKHOA JOIN KHOA K ON TRKHOA.MAGV = K.TRUONGKHOA
                     JOIN BOMON BM ON BM.MAKHOA = K.MAKHOA 
GROUP BY K.MAKHOA, TRKHOA.MAGV, TRKHOA.HOTEN, K.TENKHOA 
HAVING COUNT(BM.MABM) >= ALL(SELECT COUNT(BM2.MABM)
                             FROM BOMON BM2
                             GROUP BY BM2.MAKHOA)
UNION -- HỘI HAI KẾT QUẢ
SELECT TRKHOA.MAGV, TRKHOA.HOTEN, K.TENKHOA -- TRƯỞNG KHOA CỦA KHOA CÓ LƯƠNG TRUNG BÌNH CÁC GIÁO VIÊN CAO NHẤT
FROM GIAOVIEN TRKHOA JOIN KHOA K ON TRKHOA.MAGV = K.TRUONGKHOA
                     JOIN BOMON BM ON BM.MAKHOA = K.MAKHOA 
                     JOIN GIAOVIEN GV ON BM.MABM = GV.MABM
GROUP BY K.MAKHOA, TRKHOA.MAGV, TRKHOA.HOTEN, K.TENKHOA 
HAVING AVG(GV.LUONG) >= ALL(SELECT AVG(GV2.LUONG) 
                             FROM GIAOVIEN GV2 JOIN BOMON BM2 ON GV2.MABM = BM2.MABM
                             GROUP BY BM2.MAKHOA)
ORDER BY K.TENKHOA

--1. CÁCH 2: HỘI HAI MÃ KHOA
SELECT TRKHOA.MAGV, TRKHOA.HOTEN, K.TENKHOA
FROM GIAOVIEN TRKHOA JOIN KHOA K ON TRKHOA.MAGV = K.TRUONGKHOA
WHERE K.MAKHOA IN (SELECT BM.MAKHOA -- MÃ KHOA CỦA KHOA NHIỀU BỘ MÔN NHẤT
                   FROM BOMON BM
                   GROUP BY BM.MAKHOA
                   HAVING COUNT(BM.MABM) >= ALL(SELECT COUNT(BM2.MABM)-- ĐẾM SỐ LƯỢNG BỘ MÔN TỪNG KHOA
                                                FROM BOMON BM2
                                                GROUP BY BM2.MAKHOA)
                   UNION
                   SELECT BM.MAKHOA
                   FROM BOMON BM JOIN GIAOVIEN GV ON BM.MABM = GV.MABM
                   GROUP BY BM.MAKHOA
                   HAVING AVG(GV.LUONG) >= ALL(SELECT AVG(GV2.LUONG) -- MÃ KHOA CỦA KHOA CÓ LƯƠNG TRUNG BÌNH CÁC GIÁO VIÊN TỪNG KHOA
                                               FROM GIAOVIEN GV2 JOIN BOMON BM2 ON GV2.MABM = BM2.MABM
                                               GROUP BY BM2.MAKHOA))
ORDER BY K.TENKHOA

--1. CÁCH 3: DÙNG OR IN THAY CHO HỘI
SELECT TRKHOA.MAGV, TRKHOA.HOTEN, K.TENKHOA
FROM GIAOVIEN TRKHOA JOIN KHOA K ON TRKHOA.MAGV = K.TRUONGKHOA
WHERE K.MAKHOA IN (SELECT BM.MAKHOA -- MÃ KHOA CỦA KHOA NHIỀU BỘ MÔN NHẤT
                   FROM BOMON BM
                   GROUP BY BM.MAKHOA
                   HAVING COUNT(BM.MABM) >= ALL(SELECT COUNT(BM2.MABM)-- ĐẾM SỐ LƯỢNG BỘ MÔN TỪNG KHOA
                                                FROM BOMON BM2
                                                GROUP BY BM2.MAKHOA))
   OR K.MAKHOA IN (SELECT BM.MAKHOA
                   FROM BOMON BM JOIN GIAOVIEN GV ON BM.MABM = GV.MABM
                   GROUP BY BM.MAKHOA
                   HAVING AVG(GV.LUONG) >= ALL(SELECT AVG(GV2.LUONG) -- MÃ KHOA CỦA KHOA CÓ LƯƠNG TRUNG BÌNH CÁC GIÁO VIÊN TỪNG KHOA
                                               FROM GIAOVIEN GV2 JOIN BOMON BM2 ON GV2.MABM = BM2.MABM
                                               GROUP BY BM2.MAKHOA))
ORDER BY K.TENKHOA

-- ==> TTA IN (...) OR TTA IN (...) CÓ THỂ DÙNG THAY THỂ CHO PHÉP HỘI UNION


--2. CHO GIÁO VIÊN (MÃ GV, HỌ TÊN) CỦA GIÁO VIÊN CÓ 
--   THAM GIA ĐỀ TÀI CẤP TRƯỜNG NHƯNG KHÔNG CHỦ NHIỆM ĐỀ TÀI NÀO CẤP TRƯỜNG
--2. CÁCH 1: DÙNG EXCEPT 
-- DS GIÁO VIÊN CÓ THAM GIA ĐỀ TÀI CẤP TRƯỜNG: 001, 003, 009
SELECT DISTINCT GV.* 
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
                 JOIN DETAI DT ON TG.MADT = DT.MADT 
WHERE DT.CAPQL = N'TRƯỜNG'
EXCEPT
-- DS GIÁO VIÊN CÓ CHỦ NHIỆM ĐỀ TÀI CẤP TRƯỜNG: 001, 002, 007
SELECT DISTINCT GV.* 
FROM GIAOVIEN GV JOIN DETAI DT ON DT.GVCNDT = GV.MAGV
WHERE DT.CAPQL = N'TRƯỜNG'

--2. CÁCH 2: DÙNG NOT IN
SELECT DISTINCT GV.* -- DS GIÁO VIÊN CÓ THAM GIA ĐỀ TÀI CẤP TRƯỜNG
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
                 JOIN DETAI DT ON TG.MADT = DT.MADT 
WHERE DT.CAPQL = N'TRƯỜNG'
AND GV.MAGV NOT IN (SELECT DT.GVCNDT -- DS MÃ GIÁO VIÊN CÓ CHỦ NHIỆM ĐỀ TÀI CẤP TRƯỜNG
                    FROM DETAI DT 
                    WHERE DT.CAPQL = N'TRƯỜNG')

--2. CÁCH 3: DÙNG NOT EXISTS
SELECT DISTINCT GV.* -- DS GIÁO VIÊN CÓ THAM GIA ĐỀ TÀI CẤP TRƯỜNG
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
                 JOIN DETAI DT ON TG.MADT = DT.MADT 
WHERE DT.CAPQL = N'TRƯỜNG'
AND NOT EXISTS (SELECT * -- KIỂM TRA KHÔNG TỒN TẠI ĐỀ TÀI CẤP TRƯỜNG CÓ GVCNDT LÀ GV ĐANG XÉT
                FROM DETAI DT 
                WHERE DT.CAPQL = N'TRƯỜNG' AND DT.GVCNDT = GV.MAGV) -- TRUY VẤN LỒNG TƯƠNG QUAN DO SỬ DỤNG GV Ở TRUY VẤN CHA

-- ==> NOT IN HAY NOT EXISTS CÓ THỂ DÙNG THAY THẾ CHO PHÉP TRỪ EXCEPT

--3. CHO TRƯỞNG BỘ MÔN CÓ CHỦ NHIỆM ÍT NHẤT MỘT ĐỀ TÀI CẤP NHÀ NƯỚC 
--   VÀ CÓ THAM GIA BẤT KỲ ĐỀ TÀI NÀO CÓ CÔNG VIỆC LIÊN QUAN ĐẾN "NUÔI CẤY".
--3. CÁCH 1: DÙNG INTERSECT
SELECT TRBM.*, BM.TENBM
FROM BOMON BM JOIN GIAOVIEN TRBM ON BM.TRUONGBM = TRBM.MAGV 
WHERE TRBM.MAGV IN 
            (SELECT DT.GVCNDT -- MÃ GIÁO VIÊN CHỦ NHIỆM ĐỀ TÀI CẤP NHÀ NƯỚC:004
             FROM DETAI DT WHERE DT.CAPQL = N'NHÀ NƯỚC'
             INTERSECT 
             SELECT TG.MAGV -- MÃ GIÁO VIÊN CÓ THAM GIA ĐỀ TÀI CÓ CÔNG VIỆC NUÔI CẤY
             FROM THAMGIADT TG JOIN CONGVIEC CV ON TG.MADT = CV.MADT AND TG.STT = CV.SOTT
             WHERE CV.TENCV LIKE N'%NUÔI CẤY%'
             )


--3. CÁCH 2: DÙNG KẾT
SELECT DISTINCT TRBM.*
FROM BOMON BM JOIN GIAOVIEN TRBM ON BM.TRUONGBM = TRBM.MAGV 
              JOIN DETAI DTCN ON DTCN.GVCNDT = TRBM.MAGV -- ĐỀ TÀI MÀ TRBM LÀM CHỦ NHIỆM
              JOIN THAMGIADT TG ON TRBM.MAGV = TG.MAGV -- DỮ LIỆU THAM GIA ĐỀ TÀI CỦA TRBM
              JOIN CONGVIEC CV ON TG.MADT = CV.MADT AND TG.STT = CV.SOTT
WHERE DTCN.CAPQL = N'NHÀ NƯỚC' AND CV.TENCV LIKE N'%NUÔI CẤY%'

-- ==> PHÉP KẾT CÓ THỂ THAY THẾ CHO PHÉP GIAO INTERSECT