USE MASTER
GO
IF DB_ID('QLDETAI') IS NOT NULL
    DROP DATABASE QLDETAI
GO

--TẠO CSDL
CREATE DATABASE QLDETAI
GO

USE QLDETAI
GO

--TẠO BẢNG 
CREATE TABLE GIAOVIEN
(
    MAGV CHAR(5),
    HOTEN NVARCHAR(40),
    LUONG FLOAT,
    PHAI NVARCHAR(3),
    NGSINH DATE,
    DIACHI NVARCHAR(100),
    GVQLCM CHAR(5),
    MABM NCHAR(5),

    CONSTRAINT PK_GIAOVIEN
    PRIMARY KEY(MAGV)
)

CREATE TABLE GV_DT
(
    MAGV CHAR(5),
    DIENTHOAI CHAR(12),

    CONSTRAINT PK_GV_DT
    PRIMARY KEY(MAGV, DIENTHOAI)
)

CREATE TABLE BOMON
(
    MABM NCHAR(5),
    TENBM NVARCHAR(40),
    PHONG CHAR(5),
    DIENTHOAI CHAR(12),
    TRUONGBM CHAR(5),
    MAKHOA CHAR(4),
    NGAYNHANCHUC DATE,

    CONSTRAINT PK_BOMON
    PRIMARY KEY(MABM)
)

CREATE TABLE KHOA
(
    MAKHOA CHAR(4),
    TENKHOA NVARCHAR(40),
    NAMTL INT,
    PHONG CHAR(5),
    DIENTHOAI CHAR(12),
    TRUONGKHOA CHAR(5),
    NGAYNHANCHUC DATE,

    CONSTRAINT PK_KHOA
    PRIMARY KEY(MAKHOA)
)

CREATE TABLE DETAI
(
    MADT CHAR(3),
    TENDT NVARCHAR(100),
    CAPQL NVARCHAR(40),
    KINHPHI FLOAT,
    NGAYBD DATE,
    NGAYKT DATE,
    MACD NVARCHAR(4),
    GVCNDT CHAR(5),

    CONSTRAINT PK_DETAI
    PRIMARY KEY(MADT)
)

CREATE TABLE CHUDE
(
    MACD NVARCHAR(4),
    TENCD NVARCHAR(50),

    CONSTRAINT PK_CHUDE
    PRIMARY KEY(MACD)
)

CREATE TABLE CONGVIEC
(
    MADT CHAR(3),
    SOTT INT,
    TENCV NVARCHAR(40),
    NGAYBD DATE,
    NGAYKT DATE,

    CONSTRAINT PK_CONGVIEC
    PRIMARY KEY(MADT, SOTT)
)

CREATE TABLE THAMGIADT
(
    MAGV CHAR(5),
    MADT CHAR(3),
    STT INT,
    PHUCAP FLOAT,
    KETQUA NVARCHAR(40),

    CONSTRAINT PK_THAMGIADT
    PRIMARY KEY(MAGV, MADT, STT)
)

CREATE TABLE NGUOITHAN
(
    MAGV CHAR(5),
    TEN NVARCHAR(20),
    NGSINH DATE,
    PHAI NVARCHAR(3),

    CONSTRAINT PK_NGUOITHAN
    PRIMARY KEY(MAGV, TEN)
)

--TAO RANG BUOC
ALTER TABLE GIAOVIEN
ADD
    CONSTRAINT FK_GIAOVIEN_GIAOVIEN
    FOREIGN KEY(GVQLCM)
    REFERENCES GIAOVIEN,

    CONSTRAINT FK_GIAOVIEN_BOMON
    FOREIGN KEY(MABM)
    REFERENCES BOMON

ALTER TABLE GV_DT
ADD
    CONSTRAINT FK_GV_DT_GIAOVIEN
    FOREIGN KEY(MAGV)
    REFERENCES GIAOVIEN

ALTER TABLE BOMON
ADD 
    CONSTRAINT FK_BOMON_GIAOVIEN
    FOREIGN KEY(TRUONGBM)
    REFERENCES GIAOVIEN,

    CONSTRAINT FK_BOMON_KHOA
    FOREIGN KEY(MAKHOA)
    REFERENCES KHOA

ALTER TABLE KHOA
ADD 
    CONSTRAINT FK_KHOA_GIAOVIEN
    FOREIGN KEY(TRUONGKHOA)
    REFERENCES GIAOVIEN

ALTER TABLE NGUOITHAN
ADD 
    CONSTRAINT FK_NGUOITHAN_GIAOVIEN
    FOREIGN KEY(MAGV)
    REFERENCES GIAOVIEN

ALTER TABLE THAMGIADT
ADD 
    CONSTRAINT FK_THAMGIADT_GIAOVIEN
    FOREIGN KEY(MAGV)
    REFERENCES GIAOVIEN,

    CONSTRAINT FK_THAMGIADT_CONGVIEC
    FOREIGN KEY(MADT,STT)
    REFERENCES CONGVIEC

ALTER TABLE CONGVIEC
ADD 
    CONSTRAINT FK_CONGVIEC_DETAI
    FOREIGN KEY(MADT)
    REFERENCES DETAI

ALTER TABLE DETAI 
ADD 
    CONSTRAINT FK_DETAI_GIAOVIEN
    FOREIGN KEY(GVCNDT)
    REFERENCES GIAOVIEN,

    CONSTRAINT FK_DETAI_CHUDE
    FOREIGN KEY(MACD)
    REFERENCES CHUDE


SELECT*
FROM GIAOVIEN
SELECT*
FROM GV_DT
SELECT*
FROM BOMON
SELECT*
FROM KHOA
SELECT*
FROM DETAI
SELECT*
FROM CHUDE
SELECT*
FROM CONGVIEC
SELECT*
FROM THAMGIADT
SELECT*
FROM NGUOITHAN





