-- MSSV: 22127085
-- Họ Tên: Nguyễn Hồ Đăng Duy
-- Lớp: 22CLC09
-- Hàng: 2
-- Cột: 8
-- Mã đề: 2

USE QLDETAI
GO

--1-- 
SELECT GV.*
FROM GIAOVIEN GV 
WHERE EXISTS (SELECT GV1.MAGV 
                    FROM GIAOVIEN GV1 JOIN THAMGIADT TG ON GV1.MAGV=TG.MAGV
                    JOIN DETAI DT ON TG.MADT = DT.MADT
                    JOIN CHUDE CD ON CD.MACD = DT.MACD
                    WHERE CD.TENCD  = N'Quản lý giáo dục' AND GV.MAGV = TG.MAGV)

--2--
SELECT DT.*
FROM DETAI DT
WHERE NOT EXISTS (SELECT SDT.MAGV
				  FROM GV_DT SDT
				  GROUP BY SDT.MAGV
				  HAVING COUNT(*) >= 2
				  EXCEPT
				  SELECT TGDT.MAGV
				  FROM THAMGIADT TGDT
				  WHERE DT.MADT = TGDT.MADT)
--3-- 
GO
CREATE OR ALTER FUNCTION fnDem_SLDeTai_Khoa (@MAKHOA CHAR(5), @THANG INT, @NAM INT)
RETURNS INT 
AS 
	BEGIN
	RETURN (SELECT COUNT(*)
	FROM DETAI DT JOIN GIAOVIEN GV ON DT.GVCNDT = GV.MAGV 
		JOIN BOMON BM ON GV.MABM = BM.MABM 
	WHERE BM.MAKHOA = @MAKHOA
			AND NOT ((MONTH(DT.NGAYBD) > @Thang AND YEAR(DT.NGAYBD) = @Nam) 
				OR (MONTH(DT.NGAYKT) < @Thang AND YEAR(DT.NGAYKT) = @Nam) 
				OR (YEAR(DT.NGAYBD) >@Nam) 
				OR (YEAR(DT.NGAYKT) < @Nam)))
	END
GO

print dbo.fnDem_SLDeTai_Khoa('CNTT', 8, 2008)

--4--
GO
CREATE OR ALTER PROCEDURE spTK_SLDeTai_Khoa @MAKHOA CHAR(5), @NAM INT
AS
BEGIN 
	IF( @NAM > YEAR(GETDATE()))
	BEGIN
		RAISERROR('Năm không hợp lệ', 16, 1);
		RETURN;
	END
	IF (NOT EXISTS(SELECT *FROM KHOA WHERE KHOA.MAKHOA=@MAKHOA))
	BEGIN 
		RAISERROR('Mã khoa không hợp lệ',16,1);
		RETURN;
	END

	CREATE TABLE RESULT
	(
		THANG int, 
		SLDT int
	)
	DECLARE @I int 
	SET @I = 1; 
	WHILE (@I <= 12)
	BEGIN
		INSERT INTO Result 
		VALUES ( @I, dbo.fnDem_SLDeTai_Khoa(@MAKHOA, @I, @NAM))
		SET @I = @I + 1
	END 
	SELECT * FROM RESULT where SLDT > 0;
	DECLARE @TONG INT
	SELECT @TONG = SUM(SLDT) FROM RESULT;
	DROP TABLE RESULT
	PRINT @TONG
	RETURN @TONG
END
GO

EXEC dbo.spTK_SLDeTai_Khoa 'CNTT', 2008