--MA DE: 31
--MSSV: 22127085
--HO TEN: NGUYEN HO DANG DUY

USE MASTER
GO

IF DB_ID('QLSACH') IS NOT NULL
    DROP DATABASE QLSACH
GO

CREATE DATABASE QLSACH
GO

USE QLSACH 
GO

CREATE TABLE SACH
(
    MASACH     CHAR(4),
    TENSACH    NVARCHAR(50),
    SOLUONG    INT,
    DONGIA     INT,
    MALOAI     CHAR(2),
    KHTIEUBIEU INT

        CONSTRAINT PK_SACH 
    PRIMARY KEY (MASACH)
)

CREATE TABLE KHACHHANG
(
    MALOAI CHAR(2),
    STT    INT,
    HOTEN  NVARCHAR(50),
    DIACHI NVARCHAR(50)

        CONSTRAINT PK_KHACHHANG
    PRIMARY KEY (MALOAI, STT)
)

CREATE TABLE MUAHANG
(
    LOAIKH  CHAR(2),
    SOTT    INT,
    MASACH  CHAR(4),
    NGAYMUA DATE,
    SOLUONG INT,
    DONGIA  INT

        CONSTRAINT PK_MUAHANG
    PRIMARY KEY (LOAIKH, SOTT, MASACH)
)

ALTER TABLE SACH 
ADD 
    CONSTRAINT FK_SACH_KHACHHANG
    FOREIGN KEY (MALOAI, KHTIEUBIEU)
    REFERENCES KHACHHANG(MALOAI, STT)

ALTER TABLE MUAHANG
ADD
    CONSTRAINT FK_MUAHANG_KHACHHANG
    FOREIGN KEY (LOAIKH, SOTT)
    REFERENCES KHACHHANG(MALOAI, STT),

    CONSTRAINT FK_MUAHANG_SACH
    FOREIGN KEY (MASACH)
    REFERENCES SACH(MASACH)

INSERT KHACHHANG
VALUES
    ('L1', 1, N'Nguyễn Thị Minh', N'123 Vườn Lài, Tân Phú'),
    ('L1', 2, N'Trần Trung Nghĩa', N'45 Phú Thọ Hòa, Tân Phú'),
    ('L2', 1, N'Vũ Ánh Nguyệt', N'11 Võ Văn Ngân, Thủ Đức')

INSERT SACH
VALUES
    ('S001', N'Đồi Thỏ', 1000, 97000, 'L1', 1),
    ('S002', N'Bài giảng cuối cùng', 24, 102000, 'L2', 1)

INSERT MUAHANG
VALUES
    ('L1', 1, 'S001', '2/12/2009', 30, 90000),
    ('L1', 2, 'S001', '12/30/2019', 20, 87000),
    ('L2', 1, 'S002', '6/6/2016', 10, 100000),
    ('L1', 2, 'S002', '3/7/2018', 5, 120000)

SELECT * FROM SACH
SELECT * FROM KHACHHANG
SELECT * FROM MUAHANG

--Q4
SELECT KH.*, SUM(MH.DONGIA) AS TONGHOADON
FROM KHACHHANG KH JOIN MUAHANG MH ON KH.MALOAI = MH.LOAIKH AND KH.STT = MH.SOTT
GROUP BY KH.MALOAI, KH.STT, KH.HOTEN, KH.DIACHI

--Q5
SELECT KH.* 
FROM KHACHHANG KH JOIN MUAHANG MH ON KH.MALOAI = MH.LOAIKH AND KH.STT = MH.SOTT
WHERE KH.HOTEN LIKE N'NGUYỄN %' AND YEAR(MH.NGAYMUA) = 2009 AND MONTH(MH.NGAYMUA) = 12 AND MH.SOLUONG > 10


--MA DE: 33
--MSSV: 22127085
--HO TEN: NGUYEN HO DANG DUY

USE MASTER
GO

IF DB_ID('QLPHONGTHI') IS NOT NULL
    DROP DATABASE QLPHONGTHI
GO

CREATE DATABASE QLPHONGTHI
GO

USE QLPHONGTHI
GO


CREATE TABLE GIAOVIEN 
(
    MAGV CHAR(5),
    TENGV NVARCHAR(50),
    DIACHI NVARCHAR(50),
    VAITRO NVARCHAR(50)

    CONSTRAINT PK_GIAOVIEN
    PRIMARY KEY (MAGV)
)

CREATE TABLE PHONGTHI
(
    IDPHONG CHAR(4),
    IDDIEMTHI CHAR(3),
    CANBO CHAR(5),
    SOBAN INT, 
    THIETBI NVARCHAR(50)

    CONSTRAINT PK_PHONGTHI
    PRIMARY KEY (IDPHONG, IDDIEMTHI),
)

CREATE TABLE THISINH
(
    SBD CHAR(4),
    DIEMTHI CHAR (3),
    HOTEN NVARCHAR(50),
    DIACHI NVARCHAR(50),
    NGAYSINH DATE,
    PHONGTHI CHAR(4)


    CONSTRAINT PK_THISINH
    PRIMARY KEY (SBD)
)

ALTER TABLE PHONGTHI
ADD 
    CONSTRAINT FK_PHONGTHI_GIAOVIEN
    FOREIGN KEY (CANBO)
    REFERENCES GIAOVIEN(MAGV)

ALTER TABLE THISINH
ADD 
    CONSTRAINT FK_THISINH_PHONGTHI
    FOREIGN KEY (PHONGTHI, DIEMTHI)
    REFERENCES PHONGTHI(IDPHONG, IDDIEMTHI)

INSERT GIAOVIEN
VALUES 
    ('GV001', N'Trần Thị Bé', N'31 Nguyễn Xí Q.Bình Thạnh', N'Cán bộ'),
    ('GV002', N'Nguyễn Minh Tâm', N'2 Trần Hưng Đạo Q5', N'Giám sát'),
    ('GV003', N'Trần Văn Lí', N'30 Hà Tồn QUyền Q5', N'Cán bộ')

INSERT PHONGTHI
VALUES
    ('P001', 'DD1', 'GV001', 25, N'Mic-Loa-Tivi'),
    ('P002', 'DD1', 'GV002', 30, N'Mic-Loa-Tivi'),
    ('P001', 'DD2', 'GV003', 15, NULL)

INSERT THISINH
VALUES 
    ('0231', 'DD1', N'Nguyễn Quan Tùng', N'TPHCM', '11/30/2000', 'P001'),
    ('0230', 'DD2', N'Lưu Phi Nam', N'Hải Phòng', '2/12/2000', 'P001'),
    ('0234', 'DD1', N'Lê Quang Bảo', N'Hà Nội', '2/13/2000', 'P002'),
    ('0233', 'DD2', N'Hà Ngọc Thúy', N'TPHCM', '4/24/2000', 'P001')

SELECT * FROM GIAOVIEN
SELECT * FROM PHONGTHI
SELECT * FROM THISINH

--Q4
SELECT PT.IDPHONG, GV.TENGV, COUNT(TS.PHONGTHI) AS SOLUONG
FROM PHONGTHI PT JOIN THISINH TS ON PT.IDPHONG = TS.PHONGTHI AND PT.IDDIEMTHI = TS.DIEMTHI
    JOIN GIAOVIEN GV ON PT.CANBO = GV.MAGV
GROUP BY PT.IDPHONG, GV.TENGV

--Q5
SELECT PT.*, GV.TENGV
FROM PHONGTHI PT JOIN GIAOVIEN GV ON PT.CANBO = GV.MAGV
    JOIN THISINH TS ON PT.IDPHONG = TS.PHONGTHI AND PT.IDDIEMTHI = TS.DIEMTHI
WHERE TS.DIACHI = N'Hải Phòng'
GROUP BY PT.IDPHONG, PT.IDDIEMTHI, PT.CANBO, PT.SOBAN, PT.THIETBI, GV.TENGV
HAVING PT.SOBAN > 15 
