USE QLDETAI 
GO

-- 1. Xuất mã và họ tên giáo viên có tham gia đề tài do trưởng bộ môn của họ là chủ nhiệm.
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
    JOIN DETAI DT ON TG.MADT=DT.MADT
    JOIN BOMON BM ON BM.MABM = GV.MABM
    JOIN GIAOVIEN TBM ON BM.TRUONGBM = TBM.MAGV
WHERE DT.GVCNDT = TBM.MAGV

-- 2. Xuất mã, họ tên, và tuổi của các giáo viên đã từng tham gia công việc thiết kế hoặc đã 
-- từng chủ nhiệm đề tài có công việc liên quan đến xác định yêu cầu.
    SELECT GV.MAGV, GV.HOTEN, DATEDIFF(YEAR, GV.NGSINH, GETDATE()) AS TUOI
    FROM GIAOVIEN GV
        JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
        JOIN CONGVIEC CV ON (TG.MADT = CV.MADT AND TG.STT = CV.SOTT)
    WHERE CV.TENCV LIKE N'THIẾT KẾ%'
UNION
    SELECT GV.MAGV, GV.HOTEN, DATEDIFF(YEAR, GV.NGSINH, GETDATE()) AS TUOI
    FROM GIAOVIEN GV JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
        JOIN THAMGIADT TG ON TG.MADT = DT.MADT
        JOIN CONGVIEC CV ON (TG.MADT = CV.MADT AND TG.STT = CV.SOTT)
    WHERE CV.TENCV LIKE N'XÁC ĐỊNH YÊU CẦU%'

-- 3. Xuất mã và họ tên các trưởng khoa có tham gia đề tài thuộc chủ đề “nghiên cứu” nhưng 
-- chưa từng tham gia đề tài nào thuộc chủ đề “ứng dụng”.
    SELECT DISTINCT GV.MAGV, GV.HOTEN
    FROM GIAOVIEN GV JOIN KHOA K ON GV.MAGV = K.TRUONGKHOA
        JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
        JOIN DETAI DT ON TG.MADT = DT.MADT
        JOIN CHUDE CD ON DT.MACD = CD.MACD
    WHERE CD.TENCD LIKE N'NGHIÊN CỨU%'
EXCEPT
    SELECT DISTINCT GV.MAGV, GV.HOTEN
    FROM GIAOVIEN GV JOIN KHOA K ON GV.MAGV = K.TRUONGKHOA
        JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
        JOIN DETAI DT ON TG.MADT = DT.MADT
        JOIN CHUDE CD ON DT.MACD = CD.MACD
    WHERE CD.TENCD LIKE N'ỨNG DỤNG%'

-- 4. Xuất mã, tên chủ đề, cấp quản lý (capql) và số lượng đề tài có kinh phí từ 100 triệu trở 
-- lên theo từng cấp quản lý của mỗi chủ đề. 
SELECT CD.MACD, CD.TENCD, DT.CAPQL, COUNT(DT.MADT) AS SOLUONG
FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
WHERE DT.KINHPHI >= 100
GROUP BY CD.MACD, CD.TENCD, DT.CAPQL
ORDER BY DT.CAPQL

-- 5. Xuất mã, họ tên giáo viên, họ tên quản lý chuyên môn của giáo viên (nếu không có 
-- quản lý để ký hiệu “-”) của các giáo viên có tham gia đề tài được chủ nhiệm bởi giáo 
-- viên khác bộ môn. 
SELECT GV.MAGV, GV.HOTEN, ISNULL(GV1.HOTEN, N'-') AS HOTENQLCM
FROM GIAOVIEN GV LEFT JOIN GIAOVIEN GV1 ON GV.GVQLCM = GV1.MAGV
WHERE GV.MAGV IN (SELECT DISTINCT TG.MAGV
FROM THAMGIADT TG JOIN DETAI DT ON TG.MADT = DT.MADT
    JOIN GIAOVIEN GV2 ON DT.GVCNDT = GV2.MAGV
WHERE GV.MABM != GV2.MABM)

-- 6. Xuất mã, họ tên giáo viên và tổng số lượng giáo viên mà họ quản lý chuyên môn (nếu 
-- không quản lý ai, giá trị xuất ra là 0).
SELECT GV.MAGV, GV.HOTEN, COUNT(GV1.MAGV) AS SOLUONG
FROM GIAOVIEN GV LEFT JOIN GIAOVIEN GV1 ON GV.MAGV = GV1.GVQLCM
GROUP BY GV.MAGV, GV.HOTEN

-- 7. Xuất mã, họ tên giáo viên, tên khoa mà giáo viên thuộc về của các giáo viên từng chủ 
-- nhiệm trên 2 đề tài có kinh phí >= 100 triệu. 
SELECT GV.MAGV, GV.HOTEN, K.TENKHOA
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE GV.MAGV IN (SELECT DISTINCT GV1.MAGV
FROM GIAOVIEN GV1 JOIN DETAI DT ON GV1.MAGV = DT.GVCNDT
WHERE DT.KINHPHI >= 100
GROUP BY GV1.MAGV
HAVING COUNT(DT.MADT) > 2)

-- 8. Xuất mã, tên đề tài, tên và STT công việc có đông giáo viên tham gia nhất. 
SELECT DT.MADT, DT.TENDT, CV.TENCV, CV.SOTT
FROM DETAI DT JOIN THAMGIADT TG ON DT.MADT = TG.MADT
    JOIN CONGVIEC CV ON (TG.MADT = CV.MADT AND TG.STT =CV.SOTT)
GROUP BY DT.MADT, DT.TENDT, CV.TENCV, CV.SOTT
HAVING COUNT(DISTINCT TG.MAGV) >= ALL (SELECT COUNT(DISTINCT TG1.MAGV)
FROM THAMGIADT TG1
GROUP BY TG1.MADT, TG1.STT)

-- 9. Xuất mã và họ tên giáo viên có lương lớn nhất ở từng khoa theo các yêu cầu sau: 
-- • Cách 1: Có dùng lượng từ ALL hoặc hàm kết hợp MAX.
SELECT GV.MAGV, GV.HOTEN, K.MAKHOA
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
GROUP BY GV.MAGV, GV.HOTEN, K.MAKHOA, GV.LUONG
HAVING GV.LUONG >= ALL (SELECT GV1.LUONG
FROM GIAOVIEN GV1 JOIN BOMON BM1 ON GV1.MABM = BM1.MABM
    JOIN KHOA K1 ON BM1.MAKHOA = K1.MAKHOA
WHERE K1.MAKHOA = K.MAKHOA
GROUP BY K1.MAKHOA, GV1.LUONG)
-- • Cách 2: Không dùng bất cứ lượng từ hay hàm kết hợp nào. 
SELECT GV.MAGV, GV.HOTEN, K.MAKHOA
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
GROUP BY GV.MAGV, GV.HOTEN, K.MAKHOA, GV.LUONG
HAVING NOT EXISTS (SELECT GV1.LUONG
FROM GIAOVIEN GV1 JOIN BOMON BM1 ON GV1.MABM = BM1.MABM
    JOIN KHOA K1 ON BM1.MAKHOA = K1.MAKHOA
WHERE K1.MAKHOA = K.MAKHOA AND GV1.LUONG > GV.LUONG
GROUP BY K1.MAKHOA, GV1.LUONG)

-- 10. Xuất mã và tên khoa có đông giáo viên từng chủ nhiệm đề tài nhất. 
SELECT K.MAKHOA, K.TENKHOA
FROM KHOA K JOIN BOMON BM ON K.MAKHOA = BM.MAKHOA
    JOIN GIAOVIEN GV ON BM.MABM = GV.MABM
    JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
GROUP BY K.MAKHOA, K.TENKHOA
HAVING COUNT(DISTINCT GV.MAGV) >= ALL (SELECT COUNT(DISTINCT GV1.MAGV)
FROM KHOA K1 JOIN BOMON BM1 ON K1.MAKHOA = BM1.MAKHOA
    JOIN GIAOVIEN GV1 ON BM1.MABM = GV1.MABM
    JOIN DETAI DT1 ON GV1.MAGV = DT1.GVCNDT
GROUP BY K1.MAKHOA, K1.TENKHOA)

-- 11. Xuất mã và tên bộ môn có nhiều giáo viên có quản lý chuyên môn nhất. 
SELECT BM.MABM, BM.TENBM, COUNT(DISTINCT GV.MAGV) AS SOLUONG
FROM BOMON BM JOIN GIAOVIEN GV ON BM.MABM = GV.MABM
    JOIN GIAOVIEN GVQL ON GV.MAGV = GVQL.GVQLCM
GROUP BY BM.MABM, BM.TENBM
HAVING COUNT(DISTINCT GV.MAGV) >= ALL (SELECT COUNT(DISTINCT GV1.MAGV)
                FROM BOMON BM1 JOIN GIAOVIEN GV1 ON BM1.MABM = GV1.MABM
                    JOIN GIAOVIEN GVQL1 ON GV1.MAGV = GVQL1.GVQLCM
                    GROUP BY BM1.MABM, BM1.TENBM)

-- 12. Xuất mã, họ tên giáo viên và tổng tiền phụ cấp mà giáo viên nhận được theo từng năm. 
-- Biết rằng tiền phụ cấp được tính từ hệ số phụ cấp cho các công việc mà giáo viên tham 
-- gia trong năm đó (có ngày kết thúc trong năm đang xét) với các quy định như sau: 
-- • Kết quả “Đạt”, Phụ cấp = Hệ số * Lương tháng. 
-- • Còn lại, Phụ cấp = Hệ số * (1/2 Lương tháng).
SELECT GV.MAGV, GV.HOTEN, YEAR(CV.NGAYKT) AS NAM,
    CASE WHEN TG.KETQUA = N'Đạt' THEN SUM(GV.LUONG* TG.PHUCAP)
	ELSE SUM(GV.LUONG* TG.PHUCAP * 0.5) END AS PHUCAP
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
    JOIN CONGVIEC CV ON CV.MADT = TG.MADT AND CV.SOTT = TG.STT
GROUP BY GV.MAGV,GV.HOTEN, YEAR(CV.NGAYKT),TG.KETQUA

-- 13. Xuất mã và họ tên giáo viên thuộc khoa “Công nghệ thông tin” có tham gia tất cả đề tài 
-- thuộc cấp ĐHQG.
 SELECT GV.MAGV, GV.HOTEN
 FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
    JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
    JOIN DETAI DT ON TG.MADT = DT.MADT
WHERE K.TENKHOA = N'Công nghệ thông tin' AND DT.CAPQL = N'ĐHQG'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT DT.MADT) = (SELECT COUNT(DISTINCT DT1.MADT) FROM DETAI DT1 WHERE DT1.CAPQL = N'ĐHQG')

-- 14. Xuất mã, họ tên giáo viên thuộc bộ môn “Mạng máy tính” tham gia tất cả công việc 
-- liên quan đến đề tài thuộc chủ đề “ứng dụng”. 
SELECT GV.MAGV, GV.HOTEN 
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
    JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
    JOIN CONGVIEC CV ON TG.MADT = CV.MADT AND TG.STT = CV.SOTT
    JOIN CHUDE CD ON DT.MACD = CD.MACD
WHERE BM.TENBM = N'Mạng máy tính' AND CD.TENCD LIKE N'Ứng dụng%'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT CV.SOTT) = (SELECT COUNT(DISTINCT CV1.SOTT) 
                                    FROM CONGVIEC CV1 JOIN DETAI DT1 ON CV1.MADT = DT1.MADT
                                    JOIN CHUDE CD1 ON DT1.MACD = CD1.MACD
                                    WHERE CD1.TENCD LIKE N'Ứng dụng%')

-- 15. Xuất mã, họ tên trưởng khoa có các đề tài từng chủ nhiệm bao phủ tất cả các chủ đề.
--EXCEPT 
SELECT DISTINCT GV.MAGV, GV.HOTEN 
FROM GIAOVIEN GV JOIN KHOA K ON GV.MAGV = K.TRUONGKHOA
    JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
WHERE NOT EXISTS (SELECT CD.MACD
                    FROM CHUDE CD
                    EXCEPT 
                    SELECT DISTINCT DT1.MACD 
                    FROM DETAI DT1
                    WHERE DT1.GVCNDT = GV.MAGV)
--COUNT
SELECT TK.MAGV,TK.HOTEN
FROM KHOA K JOIN BOMON BM ON BM.MAKHOA = K.MAKHOA
			JOIN GIAOVIEN TK ON TK.MAGV = K.TRUONGKHOA
			JOIN DETAI DT ON DT.GVCNDT = TK.MAGV
			JOIN CHUDE CD ON CD.MACD = DT.MACD
GROUP BY TK.MAGV,TK.HOTEN
HAVING COUNT (DISTINCT CD.MACD) = (SELECT COUNT (DISTINCT CD2.MACD) FROM CHUDE CD2)

-- 16. Xuất mã, họ tên trưởng bộ môn có các đề tài từng tham gia liên quan đến tất cả các cấp. 
SELECT GV.MAGV, GV.HOTEN 
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM
    JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
    JOIN DETAI DT ON TG.MADT = DT.MADT
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT DT.CAPQL) = (SELECT COUNT(DISTINCT DT2.CAPQL) FROM DETAI DT2)

-- 17. Xuất mã, tên chủ đề có đề tài có tất cả giáo viên có mã tận cùng là số chẵn tham gia. 
SELECT CD.MACD, CD.TENCD
FROM CHUDE CD JOIN DETAI DT ON DT.MACD = CD.MACD
    JOIN THAMGIADT TG ON TG.MADT = DT.MADT
WHERE TG.MAGV % 2 = 0
GROUP BY CD.MACD, CD.TENCD
HAVING COUNT(DISTINCT TG.MAGV) = (SELECT COUNT(GV.MAGV) FROM GIAOVIEN GV WHERE GV.MAGV % 2 = 0)

-- 18. Xuất mã, tên đề tài, tên công việc có tất cả giáo viên có lương 2000-3000 tham gia.
SELECT DT.MADT, DT.TENDT, CV.TENCV
FROM DETAI DT JOIN THAMGIADT TG ON DT.MADT = TG.MADT 
    JOIN CONGVIEC CV ON TG.MADT = CV.MADT AND TG.STT = CV.SOTT
WHERE TG.MAGV IN (SELECT GV.MAGV FROM GIAOVIEN GV WHERE GV.LUONG >= 2000 AND GV.LUONG <= 3000)
GROUP BY DT.MADT, DT.TENDT, CV.TENCV
HAVING COUNT(DISTINCT TG.MAGV) = (SELECT COUNT(GV1.MAGV) FROM GIAOVIEN GV1 WHERE GV1.LUONG >= 2000 AND GV1.LUONG <= 3000)

