--CREATE PROCEDURE SP_TONGCHANMN @M INT, @N INT
--AS 
--    DECLARE @TONG INT 
--    DECLARE @I INT
--    SET @TONG = 0
--    SET @I = @M
--    WHILE (@I <= @N)
--    BEGIN
--        IF (@I % 2 = 0)
--            SET @TONG = @TONG + @I
--        SET @I = @I + 1
--    END
--    PRINT @TONG
--GO
--EXEC SP_TONGCHANMN 1, 20

-- CREATE PROCEDURE SP_KIEMTRAGVTONTAI @MAGV CHAR(9)
-- AS
-- 	IF (EXISTS(SELECT * FROM GIAOVIEN WHERE MAGV = @MAGV))
-- 		PRINT N'GIÁO VIÊN TỒN TẠI'
-- 	ELSE 
-- 		PRINT N'KHÔNG TỒN TẠI GIÁO VIÊN ' + @MAGV
-- GO

-- EXEC SP_KIEMTRAGVTONTAI '001'

GO
CREATE OR ALTER  FUNCTION FTINHTUOI (@NGAYSINH DATE)
RETURNS INT 
AS 
BEGIN 
    RETURN YEAR(GETDATE()) - YEAR(@NGAYSINH)
END
GO

SELECT MAGV, DBO.FTINHTUOI(NGAYSINH) AS TUOI 
FROM GIAOVIEN