USE QLDETAI 
GO

-- Q35
SELECT DISTINCT GV.LUONG
FROM GIAOVIEN GV
WHERE GV.LUONG >= ALL(SELECT LUONG
FROM GIAOVIEN)

-- Q36
SELECT GV.*
FROM GIAOVIEN GV 
WHERE GV.LUONG >= ALL (SELECT GV1.LUONG FROM GIAOVIEN GV1)

-- Q37
SELECT DISTINCT GV.LUONG
FROM GIAOVIEN GV
WHERE GV.LUONG >= ALL (SELECT LUONG
FROM GIAOVIEN
WHERE MABM = 'HTTT')

-- Q38
SELECT GV.HOTEN, GV.NGSINH 
FROM GIAOVIEN GV 
WHERE DATEDIFF(YEAR, GV.NGSINH, GETDATE()) >= ALL(SELECT DATEDIFF(YEAR, GV1.NGSINH, GETDATE())
FROM GIAOVIEN GV1 JOIN BOMON BM ON GV1.MABM = BM.MABM
WHERE BM.TENBM = N'HỆ THỐNG THÔNG TIN')

-- Q39
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE K.TENKHOA = N'Công nghệ thông tin' AND
    DATEDIFF(YEAR, GV.NGSINH, GETDATE()) <= ALL (SELECT DATEDIFF(YEAR, GV1.NGSINH, GETDATE())
    FROM GIAOVIEN GV1 JOIN BOMON BM1 ON GV1.MABM = BM1.MABM
        JOIN KHOA K1 ON BM1.MAKHOA = K1.MAKHOA
    WHERE K1.TENKHOA = N'Công nghệ thông tin')

-- Q40
SELECT GV.HOTEN, K.TENKHOA
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE GV.LUONG >= ALL (SELECT GV1.LUONG FROM GIAOVIEN GV1)

-- Q41
SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.LUONG >= ALL (SELECT GV1.LUONG
FROM GIAOVIEN GV1
WHERE GV.MABM = GV1.MABM)

-- Q42
SELECT DT.TENDT
FROM DETAI DT 
WHERE DT.MADT NOT IN
(SELECT TG.MADT
FROM THAMGIADT TG JOIN GIAOVIEN GV ON TG.MAGV = GV.MAGV
WHERE GV.HOTEN = N'Nguyễn Hoài An')

-- Q43
SELECT DT.TENDT, GVCN.HOTEN AS 'GVCN'
FROM DETAI DT JOIN GIAOVIEN GVCN ON DT.GVCNDT=GVCN.MAGV
WHERE DT.MADT NOT IN
(SELECT TG.MADT
FROM THAMGIADT TG JOIN GIAOVIEN GV ON TG.MAGV = GV.MAGV
WHERE GV.HOTEN = N'Nguyễn Hoài An')

-- Q44
SELECT GV.HOTEN 
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM 
    JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
WHERE K.TENKHOA = N'Công nghệ thông tin' AND NOT EXISTS (SELECT *
FROM GIAOVIEN GV1 JOIN BOMON BM1 ON GV1.MABM = BM1.MABM 
    JOIN KHOA K1 ON K1.MAKHOA = BM1.MAKHOA
    JOIN THAMGIADT TG ON GV1.MAGV = TG.MAGV
WHERE K1.TENKHOA = N'Công nghệ thông tin')

-- Q45
SELECT GV.*
FROM GIAOVIEN GV 
WHERE GV.MAGV NOT IN (SELECT GV1.MAGV 
FROM GIAOVIEN GV1 JOIN THAMGIADT TG ON GV1.MAGV = TG.MAGV)

-- Q46
SELECT GV.*
FROM GIAOVIEN GV 
WHERE GV.LUONG > (SELECT GV1.LUONG 
FROM GIAOVIEN GV1 
WHERE GV1.HOTEN = N'Nguyễn Hoài An')

-- Q47
SELECT GV.*
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM
WHERE GV.MAGV = ANY (SELECT GV.MAGV 
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV)

-- Q48 
SELECT GV.*
FROM GIAOVIEN GV, (SELECT * FROM GIAOVIEN) GV1
WHERE GV.HOTEN = GV1.HOTEN AND GV.PHAI = GV1.PHAI AND GV.MAGV != GV1.MAGV AND GV.MABM = GV1.MABM

-- Q49
SELECT GV.*
FROM GIAOVIEN GV 
WHERE GV.LUONG > ANY (SELECT GV1.LUONG
FROM GIAOVIEN GV1 JOIN BOMON BM ON GV1.MABM = BM.MABM
WHERE BM.TENBM = N'Công nghệ phần mềm')

-- Q50
SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.LUONG > ALL (SELECT GV1.LUONG
FROM GIAOVIEN GV1 JOIN BOMON BM ON GV1.MABM = BM.MABM
WHERE BM.TENBM = N'Hệ thống thông tin')

-- Q51
SELECT K.TENKHOA
FROM KHOA K JOIN BOMON BM ON K.MAKHOA = BM.MAKHOA
    JOIN GIAOVIEN GV ON BM.MABM = GV.MABM
GROUP BY K.MAKHOA, K.TENKHOA
HAVING COUNT(*) >= ALL (SELECT COUNT(*)
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM 
JOIN KHOA K1 ON K1.MAKHOA = BM.MAKHOA
GROUP BY K1.MAKHOA)

-- Q52
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(*) >= ALL (SELECT COUNT(*)
FROM GIAOVIEN GV1 JOIN DETAI DT1 ON GV1.MAGV = DT1.GVCNDT
GROUP BY GV1.MAGV)

-- Q53
SELECT BM.MABM 
FROM BOMON BM JOIN GIAOVIEN GV ON BM.MABM = GV.MABM
GROUP BY BM.MABM
HAVING COUNT(*) >= ALL (SELECT COUNT(*)
FROM GIAOVIEN 
GROUP BY MABM)

-- Q54
SELECT GV.HOTEN, BM.TENBM
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
GROUP BY GV.HOTEN, BM.TENBM, GV.MAGV
HAVING COUNT(DISTINCT TG.MADT) >= ALL (SELECT COUNT(DISTINCT MADT) FROM THAMGIADT GROUP BY MAGV)

-- Q55
SELECT GV.HOTEN 
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM 
    JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
WHERE BM.MABM = 'HTTT'
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT MADT) >= ALL (SELECT COUNT(DISTINCT MADT)
FROM GIAOVIEN GV1 
    JOIN THAMGIADT TG1 ON GV1.MAGV = TG1.MAGV
WHERE GV1.MABM = 'HTTT'
GROUP BY GV1.MAGV)

-- Q56
SELECT GV.HOTEN, BM.TENBM
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    JOIN NGUOITHAN NT ON GV.MAGV = NT.MAGV
GROUP BY GV.HOTEN, BM.TENBM, GV.MAGV
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM NGUOITHAN GROUP BY MAGV)

-- Q57
SELECT GV.HOTEN 
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM
    JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM DETAI GROUP BY GVCNDT)
