USE QLDETAI 
GO 

-- 1.CHO TRƯỞNG KHOA (MÃ GV, HỌ TÊN, TÊN KHOA) CỦA KHOA CÓ SỐ LƯỢNG BỘ MÔN 
-- NHIỀU NHẤT HOẶC CÓ LƯƠNG TRUNG BÌNH CỦA GIÁO VIÊN CAO NHẤT.
SELECT TK.MAGV, TK.HOTEN, K.TENKHOA
FROM  BOMON BM JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
JOIN GIAOVIEN TK ON K.TRUONGKHOA = TK.MAGV 
GROUP BY K.MAKHOA, TK.MAGV, TK.HOTEN, K.TENKHOA
HAVING COUNT(BM.MABM) >=ALL (SELECT COUNT(BM.MABM) FROM BOMON BM JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
                        GROUP BY K.MAKHOA)
UNION
SELECT  TK.MAGV, TK.HOTEN, K.TENKHOA
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
JOIN GIAOVIEN TK ON K.TRUONGKHOA = TK.MAGV
GROUP BY K.MAKHOA, TK.MAGV, TK.HOTEN, K.TENKHOA
HAVING AVG(GV.LUONG) >=ALL (SELECT AVG(GV.LUONG) FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
GROUP BY K.MAKHOA)                                                              

-- 2.CHO GIÁO VIÊN (MÃ GV, HỌ TÊN) CỦA GIÁO VIÊN CÓ THAM GIA ĐỀ TÀI CẤP TRƯỜNG 
-- NHƯNG KHÔNG CHỦ NHIỆM ĐỀ TÀI NÀO CẤP TRƯỜNG.
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
WHERE TG.MADT IN (SELECT DT.MADT FROM DETAI DT WHERE DT.CAPQL = N'Trường')
EXCEPT
SELECT GV.MAGV, GV.HOTEN 
FROM GIAOVIEN GV JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
WHERE DT.CAPQL = N'TRƯỜNG'

-- 3.CHO TRƯỞNG BỘ MÔN CÓ CHỦ NHIỆM ÍT NHẤT MỘT ĐỀ TÀI CẤP NHÀ NƯỚC VÀ THAM GIA BẤT KỲ ĐỀ TÀI NÀO CÓ CÔNG VIỆC LIÊN QUAN ĐẾN "NUÔI CẤY".
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM
WHERE GV.MAGV IN (SELECT DT.GVCNDT FROM DETAI DT WHERE DT.CAPQL = N'Nhà nước')
AND GV.MAGV IN (SELECT TG.MAGV FROM THAMGIADT TG JOIN CONGVIEC CV ON (TG.MADT = CV.MADT AND TG.STT = CV.SOTT)
WHERE CV.TENCV LIKE N'%NUÔI CẤY%')


-- 4.CHO GIÁO VIÊN (MÃ, HỌ TÊN) CHỈ THAM GIA ĐỀ TÀI CẤP NHÀ NƯỚC.
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
WHERE TG.MADT IN (SELECT DT.MADT FROM DETAI DT WHERE DT.CAPQL = N'Nhà nước')
EXCEPT
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
WHERE TG.MADT IN (SELECT DT.MADT FROM DETAI DT WHERE DT.CAPQL = N'Trường' OR DT.CAPQL = N'ĐHQG')
