-- 1 --
SELECT BM.MABM, BM.TENBM, COUNT(DISTINCT GV.MAGV) as 'SLGV co DT'
FROM BOMON BM, GIAOVIEN GV, GV_DT DT
WHERE BM.MABM = GV.MABM AND GV.MAGV = DT.MAGV
GROUP BY BM.MABM, BM.TENBM
HAVING COUNT(DISTINCT GV.MAGV) >= ALL (
	SELECT COUNT(DISTINCT GV.MAGV)
	FROM BOMON BM, GIAOVIEN GV, GV_DT DT
	WHERE BM.MABM = GV.MABM AND GV.MAGV = DT.MAGV
	GROUP BY BM.MABM, BM.TENBM
	)

-- 2 -- 
SELECT GV.*
FROM GIAOVIEN GV
WHERE NOT EXISTS (
	SELECT MADT
	FROM DETAI DT, GIAOVIEN GV1
	WHERE DT.GVCNDT = GV1.MAGV AND GV1.HOTEN = N'Trương Nam Sơn'
EXCEPT
	SELECT MADT
	FROM THAMGIADT TG
	WHERE TG.MAGV = GV.MAGV
	)

-- 3 -- 
SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.MAGV IN (
	SELECT GV.MAGV
	FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
	WHERE GV.MAGV = TG.MAGV AND TG.MADT = DT.MADT AND DT.KINHPHI > 80
	GROUP BY GV.MAGV
	HAVING COUNT(DISTINCT DT.MADT) = (
		SELECT COUNT(DISTINCT TG.MADT)
		FROM THAMGIADT TG
		WHERE GV.MAGV = TG.MAGV 
		)
	)
GO

-- 4 --
CREATE OR ALTER FUNCTION fnLay_DSDeTai_GVThamGia
	( @MaGV char(3), @Tu_Ngay date, @Den_Ngay date )
RETURNS table
AS 
	RETURN SELECT tg.MaDT, COUNT(tg.STT) as SoCV
		FROM THAMGIADT tg, CONGVIEC cv
		WHERE tg.MADT = cv.MADT and tg.STT = cv.SOTT
			and tg.MAGV = @MaGV 
			and cv.NGAYBD >= @Tu_Ngay 
			and cv.NGAYKT <= @Den_Ngay
		GROUP BY tg.MaDT
		HAVING COUNT(tg.STT) >= 2;
GO

SELECT * FROM fnLay_DSDeTai_GVThamGia('001', '2009-01-01', '2009-12-01');
GO

-- 5 --
CREATE OR ALTER PROCEDURE spHienThi_DSCongViec_GVThamGia
	@MaGV char(3), @Tu_Ngay date, @Den_Ngay date
AS
BEGIN
	IF ( NOT EXISTS (SELECT * FROM GIAOVIEN WHERE MAGV = @MaGV) )
	BEGIN
		RAISERROR('Giao vien ko ton tai.', 16, 1);
		RETURN;
	END
		
	IF (@Tu_Ngay > @Den_Ngay)
	BEGIN
		RAISERROR('Tham so vao ko hop le', 16, 1);
		RETURN;
	END

	DECLARE @SoDT int;
	SELECT @SoDT = count(dt.MaDT)
	FROM fnLay_DSDeTai_GVThamGia(@MaGV, @Tu_Ngay, @Den_Ngay) AS dt;
	PRINT CONCAT(N'Số lượng đề tài thoả yêu cầu : ', @SoDT);
	IF ( @SoDT = 0 ) return;

	SELECT cv.*
	, tg.MAGV
	FROM (CONGVIEC cv 
		JOIN fnLay_DSDeTai_GVThamGia(@MaGV, @Tu_Ngay, @Den_Ngay) dt ON dt.MADT = cv.MADT)
		LEFT JOIN THAMGIADT tg ON (tg.MADT = cv.MADT and tg.STT = cv.SOTT)
	--WHERE tg.MAGV = @MaGV;
END
GO

EXEC spHienThi_DSCongViec_GVThamGia '001', '2009-01-01', '2009-12-01';

