USE QLDETAI 
GO

-- Q35
SELECT DISTINCT GV.LUONG
FROM GIAOVIEN GV
WHERE GV.LUONG >= ALL(SELECT LUONG
FROM GIAOVIEN)

-- Q37
SELECT DISTINCT GV.LUONG
FROM GIAOVIEN GV
WHERE GV.LUONG >= ALL (SELECT LUONG
FROM GIAOVIEN
WHERE MABM = 'HTTT')

-- Q39
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE K.TENKHOA = N'Công nghệ thông tin' AND
    DATEDIFF(YEAR, GV.NGSINH, GETDATE()) <= ALL (SELECT DATEDIFF(YEAR, GV1.NGSINH, GETDATE())
    FROM GIAOVIEN GV1 JOIN BOMON BM1 ON GV1.MABM = BM1.MABM
        JOIN KHOA K1 ON BM1.MAKHOA = K1.MAKHOA
    WHERE K1.TENKHOA = N'Công nghệ thông tin')

-- Q41
SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.LUONG >= ALL (SELECT GV1.LUONG
FROM GIAOVIEN GV1
WHERE GV.MABM = GV1.MABM)

-- Q43
SELECT DT.TENDT, GVCN.HOTEN AS 'GVCN'
FROM DETAI DT JOIN GIAOVIEN GVCN ON DT.GVCNDT=GVCN.MAGV
WHERE DT.MADT NOT IN
(SELECT TG.MADT
FROM THAMGIADT TG JOIN GIAOVIEN GV ON TG.MAGV = GV.MAGV
WHERE GV.HOTEN = N'Nguyễn Hoài An')
