USE QLDETAI 
GO

-- Q58. Cho biết tên giáo viên nào mà tham gia đề tài đủ tất cả các chủ đề
--EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
    JOIN DETAI DT ON TG.MADT = DT.MADT
WHERE NOT EXISTS (            SELECT CD.MACD
    FROM CHUDE CD
EXCEPT
    SELECT DT1.MACD
    FROM THAMGIADT TG1
        JOIN DETAI DT1 ON TG1.MADT = DT1.MADT
    WHERE TG1.MAGV = GV.MAGV)
--NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
    JOIN DETAI DT ON TG.MADT = DT.MADT
WHERE NOT EXISTS (SELECT *
FROM CHUDE CD
WHERE NOT EXISTS(
                        SELECT *
FROM THAMGIADT TG1 JOIN DETAI DT1 ON TG1.MADT = DT1.MADT
WHERE TG1.MAGV = GV.MAGV AND DT1.MACD = CD.MACD
                    ))
--COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
    JOIN DETAI DT ON TG.MADT = DT.MADT
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT DT.MACD) = (SELECT COUNT(*)
FROM CHUDE)
-----------------------------------------------------------------------------------------------
-- Q59. Cho biết tên đề tài nào mà được tất cả giáo viên của bộ môn HTTT tham gia
--EXCEPT
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (            SELECT GV.MAGV
    FROM GIAOVIEN GV
    WHERE GV.MABM = 'HTTT'
EXCEPT
    (SELECT TG.MAGV
    FROM THAMGIADT TG
    WHERE TG.MADT = DT.MADT))
--NOT EXISTS
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS(SELECT *
FROM GIAOVIEN GV
WHERE GV.MABM = 'HTTT'
    AND NOT EXISTS(SELECT *
    FROM THAMGIADT TG
    WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT))
--COUNT
SELECT DT.TENDT
FROM DETAI DT JOIN THAMGIADT TG ON DT.MADT = TG.MADT
WHERE TG.MAGV IN (SELECT GV.MAGV
FROM GIAOVIEN GV
WHERE GV.MABM = 'HTTT')
GROUP BY DT.TENDT, DT.MADT
HAVING COUNT(DISTINCT TG.MAGV) = (SELECT COUNT(GV.MAGV)
FROM GIAOVIEN GV
WHERE GV.MABM = 'HTTT')
-----------------------------------------------------------------------------------------------
-- Q60. Cho biết tên đề tài có tất cả giảng viên bộ môn "Hệ thống thông tin" tham gia
--EXCEPT
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (            SELECT GV.MAGV
    FROM GIAOVIEN GV
    WHERE GV.MABM = (SELECT MABM
    FROM BOMON
    WHERE TENBM = N'Hệ thống thông tin')
EXCEPT
    (SELECT TG.MAGV
    FROM THAMGIADT TG
    WHERE TG.MADT = DT.MADT))
--NOT EXISTS
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT *
FROM GIAOVIEN GV
WHERE GV.MABM = (SELECT MABM
    FROM BOMON
    WHERE TENBM = N'Hệ thống thông tin')
    AND NOT EXISTS (SELECT *
    FROM THAMGIADT TG
    WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT))
--COUNT
SELECT DT.TENDT
FROM DETAI DT JOIN THAMGIADT TG ON DT.MADT = TG.MADT
WHERE TG.MAGV IN (SELECT GV.MAGV
FROM GIAOVIEN GV
WHERE GV.MABM = (SELECT MABM
FROM BOMON
WHERE TENBM = N'Hệ thống thông tin'))
GROUP BY DT.TENDT, DT.MADT
HAVING COUNT(DISTINCT TG.MAGV) = (SELECT COUNT(GV.MAGV)
FROM GIAOVIEN GV
WHERE GV.MABM = (SELECT MABM
FROM BOMON
WHERE TENBM = N'Hệ thống thông tin'))

-- Q61. Cho biết tên giáo viên nào đã tham gia tất cả các đề tài có mã chủ đề là QLGD
--EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (            SELECT DT.MADT
    FROM DETAI DT
    WHERE DT.MACD = 'QLGD'
EXCEPT
    SELECT TG.MADT
    FROM THAMGIADT TG
    WHERE TG.MAGV = GV.MAGV)
--NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT *
FROM DETAI DT
WHERE DT.MACD = 'QLGD'
    AND NOT EXISTS (SELECT *
    FROM THAMGIADT TG
    WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT))
--COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
WHERE TG.MADT IN (SELECT DT.MADT
FROM DETAI DT
WHERE DT.MACD = 'QLGD')
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT TG.MADT) = (SELECT COUNT(DT.MADT)
FROM DETAI DT
WHERE DT.MACD = 'QLGD')
-----------------------------------------------------------------------------------------------
-- Q62. Cho biết tên giáo viên nào tham gia tất cả các đề tài mà giáo viên Trần Trà Hương đã tham gia
--EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (            SELECT DT.MADT
    FROM DETAI DT JOIN THAMGIADT TG ON DT.MADT = TG.MADT
        JOIN GIAOVIEN GV1 ON TG.MAGV= GV1.MAGV
    WHERE GV1.HOTEN = N'Trần Trà Hương'
EXCEPT
    SELECT TG1.MADT
    FROM THAMGIADT TG1
    WHERE TG1.MAGV = GV.MAGV AND GV.HOTEN != N'Trần Trà Hương')
--NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT *
FROM DETAI DT JOIN THAMGIADT TG ON DT.MADT = TG.MADT
    JOIN GIAOVIEN GV1 ON TG.MAGV= GV1.MAGV
WHERE GV1.HOTEN = N'Trần Trà Hương'
    AND NOT EXISTS (SELECT *
    FROM THAMGIADT TG1
    WHERE TG1.MAGV = GV.MAGV AND TG1.MADT = DT.MADT AND GV.HOTEN != N'Trần Trà Hương'))
--COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
WHERE TG.MADT IN (SELECT TG1.MADT
FROM THAMGIADT TG1 JOIN GIAOVIEN GV1 ON TG1.MAGV = GV1.MAGV
WHERE GV1.HOTEN = N'Trần Trà Hương' AND GV.HOTEN != N'Trần Trà Hương')
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT TG.MADT) = (SELECT COUNT(DISTINCT TG2.MADT)
FROM GIAOVIEN GV2 JOIN THAMGIADT TG2 ON TG2.MAGV = GV2.MAGV
WHERE GV2.HOTEN = N'Trần Trà Hương')
-----------------------------------------------------------------------------------------------
-- Q63. Cho biết tên đề tài nào mà được tất cả các giáo viên của bộ môn Hóa Hữu cơ tham gia
--EXCEPT
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (            SELECT GV.MAGV
    FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    WHERE BM.TENBM = N'HÓA HỮU CƠ'
EXCEPT
    SELECT TG.MAGV
    FROM THAMGIADT TG
    WHERE TG.MADT = DT.MADT)
--NOT EXISTS
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT *
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE BM.TENBM = N'HÓA HỮU CƠ'
    AND NOT EXISTS (SELECT *
    FROM THAMGIADT TG
    WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT))
--COUNT
SELECT DT.TENDT
FROM DETAI DT JOIN THAMGIADT TG ON DT.MADT = TG.MADT
WHERE TG.MAGV IN (SELECT GV.MAGV
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE BM.TENBM = N'HÓA HỮU CƠ')
GROUP BY DT.TENDT, DT.MADT
HAVING COUNT(DISTINCT TG.MAGV) = (SELECT COUNT(GV.MAGV)
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE BM.TENBM = N'HÓA HỮU CƠ')
-----------------------------------------------------------------------------------------------
-- Q64. Cho biết tên giáo viên nào mà tham gia tất cả các công việc của đề tài 006
--EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (            SELECT CV.SOTT
    FROM CONGVIEC CV
    WHERE CV.MADT = '006'
EXCEPT
    SELECT TG.STT
    FROM THAMGIADT TG
    WHERE TG.MAGV = GV.MAGV AND TG.MADT = '006')
--NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT *
FROM CONGVIEC CV
WHERE CV.MADT = '006'
    AND NOT EXISTS (SELECT *
    FROM THAMGIADT TG
    WHERE TG.MAGV = GV.MAGV AND TG.MADT = CV.MADT AND TG.STT= CV.SOTT))
--COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
WHERE TG.MADT = '006'
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(TG.MAGV) = (SELECT COUNT(CV.SOTT)
FROM CONGVIEC CV
WHERE CV.MADT = '006')
-----------------------------------------------------------------------------------------------
-- Q65. Cho biết giáo viên nào đã tham gia tất cả các đề tài của chủ đề Ứng dụng công nghệ
--EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (        SELECT DT.MADT
    FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
    WHERE CD.TENCD = N'Ứng dụng công nghệ'
EXCEPT
    SELECT TG.MADT
    FROM THAMGIADT TG
    WHERE TG.MAGV = GV.MAGV)
--NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT *
FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
WHERE CD.TENCD = N'Ứng dụng công nghệ'
    AND NOT EXISTS (SELECT *
    FROM THAMGIADT TG
    WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT))
--COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
WHERE TG.MADT IN (SELECT DT.MADT
FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
WHERE CD.TENCD = N'Ứng dụng công nghệ')
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT TG.MADT) = (SELECT COUNT(DT.MADT)
FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
WHERE CD.TENCD = N'Ứng dụng công nghệ')
-----------------------------------------------------------------------------------------------
-- Q66. Cho biết tên giáo viên nào đã tham gia tất cả các đề tài do Trần Trà Hương làm chủ nhiệm
--EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (        SELECT DT.MADT
    FROM DETAI DT JOIN GIAOVIEN GV ON DT.GVCNDT = GV.MAGV
    WHERE GV.HOTEN = N'Trần Trà Hương'
EXCEPT
    SELECT TG.MADT
    FROM THAMGIADT TG
    WHERE TG.MAGV = GV.MAGV)
--NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT *
FROM DETAI DT JOIN GIAOVIEN GV1 ON DT.GVCNDT = GV1.MAGV
WHERE GV1.HOTEN = N'Trần Trà Hương'
    AND NOT EXISTS (SELECT *
    FROM THAMGIADT TG
    WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT))
--COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
WHERE TG.MADT IN (SELECT DT.MADT
FROM DETAI DT JOIN GIAOVIEN GV1 ON DT.GVCNDT = GV1.MAGV
WHERE GV1.HOTEN = N'Trần Trà Hương')
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT TG.MADT) = (SELECT COUNT(DT.MADT)
FROM DETAI DT JOIN GIAOVIEN GV1 ON DT.GVCNDT = GV1.MAGV
WHERE GV1.HOTEN = N'Trần Trà Hương')
-----------------------------------------------------------------------------------------------
-- Q67. Cho biết tên đề tài nào mà được tất cả các giáo viên của khoa CNTT tham gia
--EXCEPT
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (        SELECT GV.MAGV
    FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    WHERE BM.MAKHOA = 'CNTT'
EXCEPT
    SELECT TG.MAGV
    FROM THAMGIADT TG
    WHERE TG.MADT = DT.MADT)
--NOT EXISTS
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT *
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE BM.MAKHOA = 'CNTT'
    AND NOT EXISTS (SELECT *
    FROM THAMGIADT TG
    WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT))
--COUNT
SELECT DT.TENDT
FROM DETAI DT JOIN THAMGIADT TG ON DT.MADT = TG.MADT
WHERE TG.MAGV IN (SELECT GV.MAGV
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE BM.MAKHOA = 'CNTT')
GROUP BY DT.TENDT, DT.MADT
HAVING COUNT(DISTINCT TG.MAGV) = (SELECT COUNT(*)
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE BM.MAKHOA = 'CNTT')
-----------------------------------------------------------------------------------------------
-- Q68. Cho biết tên giáo viên nào mà tham gia tất cả các công việc của đề tài Nghiên cứu tế bào gốc
--EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (    SELECT CV.MADT, CV.SOTT
    FROM CONGVIEC CV JOIN DETAI DT ON CV.MADT = DT.MADT
    WHERE DT.TENDT = N'NGHIÊN CỨU TẾ BÀO GỐC'
EXCEPT
    SELECT TG.MADT, TG.STT
    FROM THAMGIADT TG
    WHERE TG.MAGV = GV.MAGV)
--NOT EXISTS
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT *
                    FROM CONGVIEC CV JOIN DETAI DT ON CV.MADT = DT.MADT
                    WHERE DT.TENDT = N'NGHIÊN CỨU TẾ BÀO GỐC'
                    AND NOT EXISTS (SELECT *
                    FROM THAMGIADT TG
                    WHERE TG.MAGV = GV.MAGV AND TG.MADT = CV.MADT AND TG.STT= CV.SOTT))
--COUNT
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
WHERE TG.MADT IN (SELECT DT.MADT FROM DETAI DT 
                    WHERE DT.TENDT = N'NGHIÊN CỨU TẾ BÀO GỐC')
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(TG.MAGV) = (SELECT COUNT(CV.SOTT)
                        FROM CONGVIEC CV JOIN DETAI DT ON CV.MADT = DT.MADT
                        WHERE DT.TENDT = N'NGHIÊN CỨU TẾ BÀO GỐC')
-----------------------------------------------------------------------------------------------
-- Q69. Tìm tên các giáo viên được phân công làm tất cả các đề tài có kinh phí trên 100 triệu
--EXCEPT
SELECT GV.HOTEN 
FROM GIAOVIEN GV 
WHERE NOT EXISTS (SELECT DT.MADT 
                    FROM DETAI DT 
                    WHERE DT.KINHPHI > 100
                    EXCEPT
                    SELECT TG.MADT 
                    FROM THAMGIADT TG 
                    WHERE TG.MAGV = GV.MAGV)
--NOT EXISTS 
SELECT GV.HOTEN
FROM GIAOVIEN GV 
WHERE NOT EXISTS (SELECT * FROM DETAI DT
                    WHERE DT.KINHPHI > 100
                    AND NOT EXISTS (SELECT * FROM THAMGIADT TG
                                    WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT))
--COUNT
SELECT GV.HOTEN 
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV 
WHERE TG.MAGV IN (SELECT DT.MADT FROM DETAI DT 
                    WHERE DT.KINHPHI > 100)
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT TG.MADT) = (SELECT COUNT(DT.MADT) FROM DETAI DT 
                                    WHERE DT.KINHPHI > 100)
-----------------------------------------------------------------------------------------------
-- Q70. Cho biết tên đề tài nào mà được tất cả các giáo viên của khoa Sinh Học tham gia
--EXCEPT
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (        SELECT GV.MAGV
    FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
        JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
    WHERE K.TENKHOA = N'Sinh Học'
EXCEPT
    SELECT TG.MAGV
    FROM THAMGIADT TG
    WHERE TG.MADT = DT.MADT)
--NOT EXISTS
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT *
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE K.TENKHOA = N'Sinh Học'
    AND NOT EXISTS (SELECT *
    FROM THAMGIADT TG
    WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT))
--COUNT
SELECT DT.TENDT
FROM DETAI DT JOIN THAMGIADT TG ON DT.MADT = TG.MADT
WHERE TG.MAGV IN (SELECT GV.MAGV
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE K.TENKHOA = N'Sinh Học')
GROUP BY DT.TENDT, DT.MADT
HAVING COUNT(DISTINCT TG.MAGV) = (SELECT COUNT(*)
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE K.TENKHOA = N'Sinh Học')
-----------------------------------------------------------------------------------------------
-- Q71. Cho biết mã số, họ tên, ngày sinh của giáo viên tham gia tất cả các công việc của 
-- đề tài "Ứng dụng hóa học xanh"
--EXCEPT
SELECT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT CV.MADT, CV.SOTT
                    FROM CONGVIEC CV JOIN DETAI DT ON CV.MADT = DT.MADT 
                    WHERE DT.TENDT = N'ỨNG DỤNG HÓA HỌC XANH'
                    EXCEPT
                    SELECT TG.MADT, TG.STT
                    FROM THAMGIADT TG
                    WHERE TG.MAGV = GV.MAGV)
--NOT EXISTS
SELECT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT * FROM CONGVIEC CV JOIN DETAI DT ON CV.MADT = DT.MADT
                    WHERE DT.TENDT = N'ỨNG DỤNG HÓA HỌC XANH'
                    AND NOT EXISTS (SELECT * FROM THAMGIADT TG
                                    WHERE TG.MAGV = GV.MAGV AND TG.MADT = CV.MADT AND TG.STT= CV.SOTT))
--COUNT 
SELECT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV 
WHERE TG.MADT IN (SELECT DT.MADT FROM DETAI DT 
                    WHERE DT.TENDT = N'ỨNG DỤNG HÓA HỌC XANH')
GROUP BY GV.MAGV, GV.HOTEN, GV.NGSINH
HAVING COUNT(DISTINCT TG.MADT) = (SELECT COUNT(CV.SOTT) FROM CONGVIEC CV JOIN DETAI DT ON CV.MADT = DT.MADT
                                    WHERE DT.TENDT = N'ỨNG DỤNG HÓA HỌC XANH')
-----------------------------------------------------------------------------------------------
-- Q72. Cho biết mã số, họ tên, tên bộ môn và tên người quản lý chuyên môn của giáo viên
-- tham gia tất cả các đề tài thuộc chủ đề "Nghiên cứu phát triển"
--EXCEPT
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    JOIN GIAOVIEN GVQL ON GV.GVQLCM = GVQL.MAGV
WHERE NOT EXISTS (SELECT DT.MADT
                    FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
                    WHERE CD.TENCD = N'Nghiên cứu phát triển'
                    EXCEPT
                    SELECT TG.MADT
                    FROM THAMGIADT TG
                    WHERE TG.MAGV = GV.MAGV)
--NOT EXISTS
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    JOIN GIAOVIEN GVQL ON GV.GVQLCM = GVQL.MAGV
WHERE NOT EXISTS (SELECT * FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
                    WHERE CD.TENCD = N'Nghiên cứu phát triển'
                    AND NOT EXISTS (SELECT * FROM THAMGIADT TG
                                    WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT))
--COUNT
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    JOIN GIAOVIEN GVQL ON GV.GVQLCM = GVQL.MAGV
    JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
WHERE TG.MADT IN (SELECT DT.MADT 
                    FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
                    WHERE CD.TENCD = N'Nghiên cứu phát triển')
GROUP BY GV.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN
HAVING COUNT(DISTINCT TG.MADT) = (SELECT COUNT(*) FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
                                    WHERE CD.TENCD = N'Nghiên cứu phát triển')
