--truy vấn đơn giản
USE  QLDETAI
GO
-- > truy vấn trên 1 bảng
--5 SELECT -> CHỨA DANH SÁCH CÁC THUỘC TÍNH MÌNH CẦN IN RA MÀN HÌNH
--1 FROM -> DANH SÁCH CÁC BẢNG CHỨA THÔNG TIN CẦN (IN RA, ĐIỀU KIỆN)
--2 WHERE -> BIỂU THỨC ĐIỀU KIỆN (AND/OR) - DÙNG () ĐỂ PHÂN CẤP THỨ TỰ THỰC HIỆN CỦA CÁC ĐIỀU KIỆN
--3 GROUP BY -> ĐỂ GOM NHÓM THUỘC TÍNH
--4 HAVING -> ĐIỀU KIỆN TRÊN NHÓM
-- ORDER BY -> DANH SÁCH CÁC THUỘC TÍNH MÌNH CẦN SẮP XẾP

-- TRUY VẤN ĐƠN GIẢN NHẤT 
-- SELECT GV.MABM [MÃ BM], GV.* -> ĐỔI TÊN BẢNG SANG "MÃ BM"
SELECT GV.MABM, GV.*
-- * ĐẠI DIỆN CHO TẤT CẢ THUỘC TÍNH CỦA BẢNG
FROM GIAOVIEN GV

-- TRUY VẤN CÓ ĐIỀU KIỆN
-- VD: CHO BIẾT GIÁO VIÊN THUỘC BM=CNTT HOẶC TUỔI CỦA GV>35
SELECT GV.*--3
FROM GIAOVIEN GV--1
WHERE GV.MABM = 'HTTT' -- 2
    OR DATEDIFF(YEAR, GV.NGSINH, GETDATE()) > 35


-- TRUY VẤN LẤY DỮ LIỆU NULL
-- VD: CHO BIẾT GIÁO VIÊN (MAGV, HOTEN) KHÔNG CÓ GVQLCM
SELECT GV.MAGV, GV.HOTEN, GV.GVQLCM
FROM GIAOVIEN GV
WHERE GV.GVQLCM IS NULL
-- IS NOT NULL


-- TRUY VẤN DỮ LIỆU CHỈ BIẾT 1 PHẦN DỮ LIỆU
-- VD: CHO BIẾT GIAO VIÊN HỌ 'NGUYỄN' TÊN "AN"
SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.HOTEN LIKE N'NGUYỄN % AN'
--% ĐẠI DIỆN CHO 1 CHUỖI KHÔNG BIẾT, _ ĐẠI DIỆN CHO 1 KÝ TỰ KHÔNG BIẾT
-- VD: CHO BIẾT LƯƠNG CỦA GV CÓ TÊN LÀ 2 KÝ TỰ
SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.HOTEN LIKE N'% __'
-- WHERE GV.HOTEN LIKE N'% [AB]__' 


-- TRUY VẤN LOẠI TRÙNG DỮ LIỆU TRƯỚC KHI XUẤT RA
-- VD: CHO BIẾT LƯƠNG CỦA GIÁO VIÊN
SELECT DISTINCT LUONG
--> LOẠI TRÙNG THÌ DÙNG DISTINCT SAU SELECT
FROM GIAOVIEN GV

-- SẮP XẾP DỮ LIỆU
-- VD: XUẤT DANH SÁCH GIÁO VIÊN TĂNG THEO LƯƠNG VÀ GIẢM THEO NĂM SINH
SELECT GV.*, DATEDIFF(YEAR, GV.NGSINH, GETDATE()) TUOI
FROM GIAOVIEN GV
ORDER BY GV.LUONG ASC, YEAR(GV.NGSINH) DESC
-- ORDER BY CÓ THỂ NHÌN THẤY CÁC THUỘC TÍNH ĐƯỢC TẠO RA Ở SELECT


-------------------------------------------------
-- > TRUY VẤN TRÊN NHIỀU BẢNG
-- CẦN PHẢI NỐI 2 BẢNG LẠI THÀNH 1 BẢNG
-- VD: CHO BIẾT TÊN GIÁO VIÊN VÀ TÊN BỘ MÔN CỦA GV ĐÓ 
-- TÍCH ĐỀ CÁC + ĐIỀU KIỆN KẾT
SELECT *
FROM GIAOVIEN GV, BOMON BM
-- TÍCH ĐỀ CÁC
WHERE GV.MABM = BM.MABM
-- ĐIỀU KIỆN KẾT 

SELECT *
FROM GIAOVIEN GV, BOMON BM, KHOA K
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA
-- PHÉP KẾT => JOIN
SELECT *
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    JOIN KHOA K ON BM.MAKHOA = K.MAKHOA

--------------------------------------------------------
-- TRUY VẤN GOM NHÓM (VỚI HÀM KẾT HỢP)
-- HÀM KẾT HỢP:
-- COUNT -> ĐẾM (TRUYỀN BẤT KÌ)
-- SUM -> TÍNH TỔNG (SỐ)
-- AVG -> TÍNH TRUNG BÌNH (SỐ)
-- MIN, MAX -> TRUYỀN BẤT KÌ 
-- DÙNG GOM NHÓM KHI NÀO: KHI MÌNH CẦN TÍNH TOÁN TRÊN CÁC HÀM KẾT HỢP VÀ TÍNH TRÊN NHÓM

-- VD: CHO BIẾT MÃ BM VÀ SỐ LƯỢNG GIÁO VIÊN CỦA BỘ MÔN ĐÓ
SELECT GV.MABM, COUNT(*)
FROM GIAOVIEN GV
GROUP BY GV.MABM
-- VD: CHO BIẾT SỐ LƯỢNG GIÁO VIÊN
SELECT COUNT(*)
FROM GIAOVIEN

SELECT GV.MABM, BM.TENBM, COUNT(*)
-- TÊN THUỘC TÍNH PHẢI NẰM Ở GROUP BY HOẶC TRONG HÀM KẾT HỢP THÌ MỚI IN RA ĐƯỢC
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
GROUP BY GV.MABM, BM.TENBM

-- COUNT(*) -> ĐẾM SỐ DÒNG
-- COUNT(THUỘC TÍNH) -> ĐẾM GIÁ TRỊ THUỘC TÍNH KHÁC NULL
-- COUNT (DISTINCT THUỘC TÍNH) -> ĐẾM GIÁ TRỊ THUỘC TÍNH KHÔNG TRÙNG


SELECT COUNT(*), COUNT(GVQLCM), COUNT(DISTINCT GVQLCM)
FROM GIAOVIEN

-- TRUY VẤN ĐIỀU KIỆN TRÊN NHÓM
-- VD: CHO BIẾT TÊN BOMON CÓ TRÊN 3 GIÁO VIÊN
SELECT BM.TENBM, COUNT(*)
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
GROUP BY BM.TENBM, GV.MABM
HAVING COUNT(*) >= 3