USE  QLDETAI
GO

--Q1
SELECT GV.HOTEN, GV.LUONG
FROM GIAOVIEN GV
WHERE GV.PHAI = N'NỮ'

--Q2
SELECT GV.HOTEN, GV.LUONG*1.1 [LUONG TANG 10%]
FROM GIAOVIEN GV

--Q3 
SELECT DISTINCT GV.MAGV
FROM GIAOVIEN GV, BOMON BM
WHERE (YEAR(BM.NGAYNHANCHUC) > 1995 AND BM.TRUONGBM=GV.MAGV) OR ((GV.HOTEN LIKE N'NGUYỄN %' AND GV.LUONG > 2000))
--Q4
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
    JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE K.TENKHOA = N'Công nghệ thông tin'

--Q5
SELECT *
FROM BOMON BM JOIN GIAOVIEN GV ON BM.TRUONGBM = GV.MAGV
WHERE BM.TRUONGBM = GV.MAGV